server:
  port: 8001
spring:
  profiles:
    active: dev
  application:
    name: hobbyzhub-backend
  datasource:
    url: jdbc:mysql://localhost:3306/hobbyz_hub_schema?useSSL=false
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  activemq:
    broker-url: tcp://localhost:61616
    user:
    password:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/hobbyz_hub_database
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth:
          starttls:
            enable:
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static:
    stack:
application:
  api:
    version: 0.0.1
  organization:
    name: Tropic World Paradise
  security:
    jwtSecret:
    expirationMS: 2419200000 # expires after 28 days
  bucket:
    name:
