server:
  port: 8765
spring:
  redis:
    host: localhost
    port: 6379
  application:
    name: hobbyzhub-backend
  datasource:
    url: jdbc:mysql://localhost:3306/hobbyz_hub_schema?useSSL=false
    username: root
    password: rootUser@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/hobbyz_hub_database
  mail:
    host: smtp.gmail.com
    port: 587
    username: martbikathi@gmail.com
    password: kzrjxvcsofaaxoly
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cloud:
  aws:
    credentials:
      access-key: 'AKIAQUYSNZ3OI32HJQNU'
      secret-key: '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'
    region:
      static: us-east-1
    stack:
application:
  api:
    version: 0.0.1
  organization:
    name: Tropic World Paradise
  security:
    jwtSecret: LgFRkEdNkP4dUFYxlc4aT4J2rZ8JeEf9wNpC0gU2Qcw9LRM4kgVcvNvUTcv6rhPwLgFRkEdNkP4dUFYxlc4aT4J2rZ8JeEf9wNpC0gU2Qcw9LRM4kgVcvN
    expirationMS: 2419200000 # expires after 28 days
  bucket:
    name: stoneagebucket
